# Generated by Django 3.2.9 on 2021-12-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlapp', '0003_rename_age_movies_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='title',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
