# Generated by Django 3.2.9 on 2021-12-17 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqlapp', '0005_rating_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='birth_country',
        ),
    ]
