# Generated by Django 3.2.9 on 2021-12-17 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlapp', '0006_remove_movies_birth_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='ratings',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
