# Generated by Django 3.2.9 on 2021-12-20 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sqlapp', '0007_alter_rating_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sqlapp.filmdirector'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='rating',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sqlapp.movies'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sqlapp.user'),
        ),
    ]
