# Generated by Django 3.2.9 on 2021-12-20 03:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlapp', '0008_auto_20211220_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rating_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
