# Generated by Django 3.2.9 on 2021-12-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlapp', '0009_rating_rating_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='is_review_recent',
            field=models.BooleanField(default=False),
        ),
    ]
