# Generated by Django 4.0 on 2021-12-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlapp', '0010_rating_is_review_recent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='is_review_recent',
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating_date',
            field=models.DateField(),
        ),
    ]
