# Generated by Django 4.0 on 2021-12-20 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlapp', '0011_remove_rating_is_review_recent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
