# Generated by Django 4.0 on 2021-12-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlapp', '0012_alter_rating_rating_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
