# Generated by Django 4.0 on 2021-12-21 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sqlapp', '0013_alter_rating_rating_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewRating',
            fields=[
                ('rating_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sqlapp.rating')),
                ('feedback', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
            bases=('sqlapp.rating',),
        ),
    ]
