# Generated by Django 4.0 on 2021-12-21 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqlapp', '0014_newrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='age',
            new_name='actor_age',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='birth_country',
            new_name='actor_birth_country',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='name',
            new_name='actor_name',
        ),
        migrations.RenameField(
            model_name='filmdirector',
            old_name='age',
            new_name='director_age',
        ),
        migrations.RenameField(
            model_name='filmdirector',
            old_name='birth_country',
            new_name='director_birth_country',
        ),
        migrations.RenameField(
            model_name='filmdirector',
            old_name='name',
            new_name='director_name',
        ),
    ]
