# Generated by Django 4.0 on 2021-12-21 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqlapp', '0015_rename_age_actor_actor_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='user_name',
        ),
    ]
