# Generated by Django 4.0 on 2021-12-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlapp', '0016_rename_email_user_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating_date',
            field=models.DateTimeField(),
        ),
    ]
